analytics: {}
color:
  brandColors:
    - '#C8C8C8'
    - '#782020'
    - '#808888'
    - '#C93636'
    - '#000000'
  brandStrength: 0.810855
  lightness: 0.887481
  rhythmicContrast: 0.94606
  saturation: 0.378289
cta: {}
layout_spectrum: 0.912007
name: Leo Oliva
opengraph: {}
purpose: {}
typography_spectrum: 0.227796
